language: python
python:
  - '3.7'

# command to install dependencies
install:
  - pipenv install

services:
  - postgresql
before_script:
  - psql -c 'create database dd1t4am05632i;' -U postgres

# command to run tests
script:
  - python3 -m pytest --cov=app

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - coveralls
