language: python
python:
  - '3.7'

# command to install dependencies
install:
  - pipenv install

services:
  - postgresql
before_script:
  - psql -c 'create database dd1t4am05632i;' -U postgres

# command to run tests
script:
  - coverage run --source='app' -m pytest && coverage report && coverage html

after_success:
  - coveralls
